### ISSUE TITLE
Error: Syntax error at 'Boolean'; expected ')' at /etc/puppet/modules/ntp/manifests/init.pp:63

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/puppet.epfl_sso#21]
`Error: Syntax error at 'Boolean'; expected ')' at /etc/puppet/modules/ntp/manifests/init.pp:63`

It happens when using puppet 3.x with ntp version 6.x (See https://tickets.puppetlabs.com/browse/MODULES-4125)

It can be fixed with:
```
# wget https://github.com/puppetlabs/puppetlabs-ntp/archive/4.2.0.tar.gz
# puppet module install --force 4.2.0.tar.gz 
```

But at some point it would be better to be able to choose the puppetlabs-ntp version in function of puppet version.

**Comment by domq** [comment]
This was actually an issue with puppet.quirks and it is hopefully fixed with 3c20fc70eda1fe80c65e6b8bca456ca10ae0c61e
