### ISSUE TITLE
curl on EPFL cer : s/http/https/

### ISSUE THREAD

**Issue by mistur** [epfl-sti/puppet.epfl_sso#30]
https://github.com/epfl-sti/puppet.epfl_sso/blob/fa4845b5c06558db29df46e51872ba01cbb819ca/manifests/private/ad.pp#L76

`Error: true ; set -e -x; curl -o /usr/share/ca-certificates/epfl/epflca.cer http://certauth.epfl.ch/epflca.cer ; openssl x509 -inform der -outform pem -in /usr/share/ca-certificates/epfl/epflca.cer -out /usr/share/ca-certificates/epfl/epfl.crt; rm /usr/share/ca-certificates/epfl/epflca.cer returned 1 instead of one of [0]
`

Yoann

**Comment by domq** [comment]
Pull request plzkthxbai ☺

**Comment by domq** [comment]
PR #31 cherry-picked and released as part of [v0.5.7](https://forge.puppet.com/epflsti/epfl_sso/0.5.7/readme), thanks @mistur!
